### DISCUSSION TITLE
Using Client Payload

### DISCUSSION THREAD

**Discussion by ghost** [convictional/trigger-workflow-and-wait#99] [Q&A]
Hi Team

Could you please let me know

how to use this to trigger a workflow with workflow dispatch inputs using client payload?

Regards,
Tilak

**Comment by paveldedourek-eaton** [comment]
I made it working, you have to use following:

```
- uses: convictional/trigger-workflow-and-wait@v1.6.1
          with:
              owner: xxx
              repo: xxx
              GITHUB_TOKEN: xxx
              workflow_file_name: xxx
              ref: xxx
              client_payload: '{ "input_item" : "value" }'
```
