### ISSUE TITLE
Is it possible to trigger enterprise workflow and wait?

### ISSUE THREAD

**Issue by LakshmiRavali** [convictional/trigger-workflow-and-wait#20]
I want to trigger a enterprise github workflow from a non enterprise github workflow. Is there any way I can do this?
As I saw here, I will not be able to provide any `github_server_url`
```
- uses: convictional/trigger-workflow-and-wait@v1.3.0
  with:
    owner: keithconvictional
    repo: myrepo
    github_token: ${{ secrets.GITHUB_PERSONAL_ACCESS_TOKEN }}
    workflow_file_name: main.yml
    ref: release-branch
    wait_interval: 10
    inputs: '{}'
    propagate_failure: false
    trigger_workflow: true
    wait_workflow: true
```
