### ISSUE TITLE
[question] does "trigger-workflow-and-wait" trigger an old running ?

### ISSUE THREAD

**Issue by tranducduong1994** [convictional/trigger-workflow-and-wait#31]
First of all, I am quite new to GitHub action. I run into an issue when use trigger-workflow-and-wait to trigger another workflow

my report has 2 branches: **develop** and **main**.
and I have 2 workflow files
github-actions-demo.yml: to create a Pull Request that merge develop into main
trigger-another-workflow.yml: to trigger github-actions-demo.yml workflow

this is **trigger-another-workflow.yml**:

```
name: demo-trigger-another-workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
     # do more some steps here
  create_pr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: convictional/trigger-workflow-and-wait@v1.4.0
        with:
          owner: tranducduong1994
          repo: Practice-github-Action
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow_file_name: github-actions-demo.yml
          ref: main
          propagate_failure: false
          trigger_workflow: true
          wait_workflow: true

```

When I trigger it manually, it was successful
![image](https://user-images.githubusercontent.com/89118981/143666837-f553b7ee-7ed0-4fca-b2dc-187e49b385c1.png)

But there isn't any new Pull Request. I open and see detail, it said that:
The workflow id is [1509634586].
Conclusion is not success, its ["cancelled"].

**1509634586** is an old workflow that I cancelled manually before. Did I misunderstand something? I thought **trigger-workflow-and-wait** create a new run and trigger it.
