### ISSUE TITLE
Seems like this doesn't work in Windows

### ISSUE THREAD

**Issue by NotNils** [convictional/trigger-workflow-and-wait#36]
I am using self-hosted windows runners and I got this error while running the command

`Error: Container action is only supported on Linux`

```
...
runs-on: [self-hosted, Windows, X64]
    steps:
      - name: run tests
        uses: convictional/trigger-workflow-and-wait@v1.5.0
        with:
          github_token: ${{secrets.PAT}}
          owner: ownerX
          repo: repoX
          workflow_file_name: dispatched_tests.yml
```

```
name: Dispatched Test
on:
  workflow_dispatch
jobs:

  setup:
    runs-on: [self-hosted, Windows, X64]
    steps:
      - name: setup
        uses: actions/checkout@v2
        uses: ./.github/setup

  test:
    needs: setup
    runs-on: [self-hosted, Windows, X64]
    steps:
      - name: run tests
        uses: ./.github/test
```

**Comment by NotNils** [comment]
I guess this isn't an issue cause I can just update the job that sends the dispatch out to use ubuntu

```
...
runs-on: ubuntu-latest
    steps:
      - name: run tests
        uses: convictional/trigger-workflow-and-wait@v1.5.0
        with:
          github_token: ${{secrets.PAT}}
          owner: ownerX
          repo: repoX
          workflow_file_name: dispatched_tests.yml
```
