### ISSUE TITLE
Action doesn't complete even if triggered workflow finished successfully

### ISSUE THREAD

**Issue by Alexander-Betz** [convictional/trigger-workflow-and-wait#49]
Since yesterday I have the problem that the latest version `v1.6.0` can trigger another workflow but the action doesn't get the triggered workflow run and so it runs forever:
```
Getting workflow runs using query: event=workflow_dispatch&created=>=2022-04-13T13:21:14+00:00&actor=&per_page=100
Triggering workflow:
  workflows/test_called.yml/dispatches
  {"ref":"main","inputs":{
  "Test_input": "Test_value"
}}
Sleeping for 10 seconds
Getting workflow runs using query: event=workflow_dispatch&created=>=2022-04-13T13:21:14+00:00&actor=&per_page=100
Sleeping for 10 seconds
Getting workflow runs using query: event=workflow_dispatch&created=>=2022-04-13T13:21:14+00:00&actor=&per_page=100
Sleeping for 10 seconds
...
```
I verified the other workflow was triggered after the timestamp and it also finished successfully.
I used the action as follows:
```
- uses: convictional/trigger-workflow-and-wait@v1.6.0
  with:
    owner: my_org
    repo: my_repo
    github_token: ${{ secrets.MY_PAT }}
    workflow_file_name: test_called.yml
    client_payload: '{"Test_input": "Test_value"}'
```
Any idea why this happens and am I the only one with this problem?
I reverted back to `v1.3.0` for now which works fine.
