### ISSUE TITLE
Incorrect workflow_id when 2 matrix jobs triggers `trigger-workflow-and-wait` at the same time

### ISSUE THREAD

**Issue by hpsony94** [convictional/trigger-workflow-and-wait#61]
Hi guys,

I am facing this issue in this context:
For instance, I have 2 repositories such as 
- github.com/example/main (`main` repo)
```
name: master ci
on:
  push:
    branches:
      - 'master'
jobs:
  build_ci:
    name: build_ci
    steps:
      - run: echo "master ci"
  run_e2e:
    name: run_e2e
    strategy:
      fail-fast: false
      matrix:
        target: [test01, test02]
    needs: build_ci
    steps:
      - uses: convictional/trigger-workflow-and-wait@v1.6.3
        name: trigger ${{ matrix.target }} and wait for it
        with:
          owner: ${{ github.repository_owner }}
          repo: test
          github_token: ${{ secrets.GH_DISPATCH_TOKEN }}
          workflow_file_name: dispatch_ci.yml
          ref: master
          wait_interval: 10
          client_payload: '{"testsuite":"${{ matrix.target }}"}'
          propagate_failure: true # Fail current job if downstream job fails.
          trigger_workflow: true
          wait_workflow: true

```
- github.com/example/test (`test` repo)
```
name: Dispatch CI
on:
  workflow_dispatch:
    inputs:
      testsuite:
        description: 'a Set of test cases'
        required: true
        default: 'test01'
        type: choice
        options:
        - test01
        - test02

jobs:
  dispatch-ci:
    name: run ${{ inputs.testsuite }} test
    runs-on: ci-general
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v3
      - name: return random for testing purpose
        run: |
          sleep 5
```

The `dispatch-ci` job in `Dispatch CI` workflow has been triggered via the change of master branch in the `main` repo.

But the thing is that it triggered it successfully but the result of checking the `dispatch-ci` job is incorrect.

After reading the code, I realized that there are 2 points
- Github action returns 204 with no content in case of calling `worklows/dispatches`. I have tried locally, and it returns `204No Content`
- For the first point, `trigger_workflow()` func is implemented by comparing old and new run ID which lead to some mistakes in case of multiple triggers at the same time.

I'd like to raise this issue for further discussion to find alternative solutions which we can contribute wherever in this actions plugin or Github actions API ....
