### ISSUE TITLE
parse error

### ISSUE THREAD

**Issue by Trik16** [convictional/trigger-workflow-and-wait#80]
I cannot understand the parse error. How can I read column 17 with this output?

```
Run convictional/trigger-workflow-and-wait@v1.6.5
  with:
    owner: owner
    repo: somerepo
    github_token: ***
    github_user: user
    workflow_file_name: build-broker-service.yml
    ref: tag-and-images
    client_payload: { image_tag=test }
    propagate_failure: false
    trigger_workflow: true
    wait_workflow: true
    comment_github_token: ***
/usr/bin/docker run --name ca2e78c453d0d4b2299c9198d5ba0c465_f97808 --label 49859c --workdir /github/workspace --rm -e "INPUT_OWNER" -e "INPUT_REPO" -e "INPUT_GITHUB_TOKEN" -e "INPUT_GITHUB_USER" -e "INPUT_WORKFLOW_FILE_NAME" -e "INPUT_REF" -e "INPUT_CLIENT_PAYLOAD" -e "INPUT_PROPAGATE_FAILURE" -e "INPUT_TRIGGER_WORKFLOW" -e "INPUT_WAIT_WORKFLOW" -e "INPUT_COMMENT_GITHUB_TOKEN" -e "INPUT_WAIT_INTERVAL" -e "INPUT_COMMENT_DOWNSTREAM_URL" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/cads-deployment/cads-deployment":"/github/workspace" 49859c:a2e78c453d0d4b2299c9198d5ba0c465
parse error: Invalid numeric literal at line 1, column 17
```
 
This is the workflow build-images.yml:

```
on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Release tag'
        required: true
        default: 'test'

jobs:

  build_remote_workflow:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger remote workflow
      uses: convictional/trigger-workflow-and-wait@v1.6.5
      with:
        owner: owner
        repo: somerepo
        github_token: ${{ secrets.CADS_PAT }}
        github_user: user
        workflow_file_name: build-broker-service.yml
        ref: tag-and-images
        client_payload: '{ image_tag=${{ github.event.inputs.image_tag }} }'
        propagate_failure: false
        trigger_workflow: true
        wait_workflow: true
```

this is the workflow that should be triggered:

```
on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Image tag'
        required: true
        default: 'latest'
  workflow_run:
    workflows: 
      - owner/otherepo/build-images.yml
    types: [requested]

```
