### ISSUE TITLE
Intermittently getting Bad Credentials

### ISSUE THREAD

**Issue by bernardomk** [convictional/trigger-workflow-and-wait#81]
Hello,

We're intermittently getting bad credentials while using this action. This is our snippet:

```yaml
      - name: Trigger SDK Build
        if: (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop')  
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: <our org>
          repo: <our repo>
          github_token: ${{ secrets.DAIS_DEVOPS_TEAM_ACTIONS_PERSONAL_ACCESS_TOKEN }}
          workflow_file_name: main.yml
          wait_workflow: false
          ref: master
```

Error in the attached log file.

Thanks.

[trigger-sdk-build.log](https://github.com/convictional/trigger-workflow-and-wait/files/10571236/trigger-sdk-build.log)
