### ISSUE TITLE
Is it possible to add example with valid payload which trigger and wait for workflow in other repository?

### ISSUE THREAD

**Issue by danieltalmor369** [convictional/trigger-workflow-and-wait#82]
I provided a json string 
```yml
- name: Execute deployment and wait for finish
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: ME
          repo: my-workflows
          github_token: ${{ secrets. GITHUB_TOKEN }}
          github_user: ${{ github.event.client_payload.actor }}
          workflow_file_name: deployment.yml
          ref: ${{ github.event.inputs.ref }}
          client_payload: '{"ref": "master", "inputs": {"repository": "${{ github.event.inputs.repository }}", "ref": "${{ github.event.inputs.ref }}", "environment": "${{ github.event.inputs.environment }}", "service_to_deploy": "${{ github.event.inputs.service_to_deploy }}"}}'

```

But I get an error on the payload:
```
curl: (22) The requested URL returned error: 422 is not a string
```
